apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: products
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://zyozgke1992_db_user:GrowShop@products-db-cluster.9wjnrah.mongodb.net/GrowShop?retryWrites=true&w=majority&tls=true"
  SPRING_DATA_MONGODB_URI: "mongodb+srv://zyozgke1992_db_user:GrowShop@products-db-cluster.9wjnrah.mongodb.net/GrowShop?retryWrites=true&w=majority&tls=true"
  MONGO_URI: "mongodb+srv://zyozgke1992_db_user:GrowShop@products-db-cluster.9wjnrah.mongodb.net/GrowShop?retryWrites=true&w=majority&tls=true"
