apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: products
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_APPLICATION_NAME: "products-api"
  MONGO_DATABASE: "GrowShop"
  SPRING_DATA_MONGODB_DATABASE: "GrowShop"
  APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4200,http://localhost:8080"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_API_DOCS_PATH: "/v3/api-docs"
