# ============================================================
# Configuración del Servidor
# ============================================================
server.port=8080

# ============================================================
# Metadata de la API (OpenAPI / Swagger)
# ============================================================
api.info.title=Products API
api.info.description=Microservicio CRUD de Productos construido con Spring Boot 3, Java 21 y MySQL. Arquitectura Hexagonal
api.info.version=0.0.1-SNAPSHOT
api.info.contact.name=Nelson Parra - 1010205795
api.info.contact.email=njaparrah@poligran.edu.co
api.info.contact.url=https://github.com/zyozmen/Products
api.info.license.name=MIT License
api.info.license.url=https://opensource.org/licenses/MIT

# Ruta de la UI de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta del JSON de la especificación OpenAPI
springdoc.api-docs.path=/v3/api-docs

# ============================================================
# Configuración de JPA / Hibernate
# ============================================================

spring.jpa.hibernate.ddl-auto=update

# se evita que se muestren las consultas SQL en la consola para no saturar los logs
spring.jpa.show-sql=true

# Formatea el SQL para que sea más legible en los logs
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico de MySQL 8 para que Hibernate genere SQL optimizado
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Nombre de la base de datos al que Hibernate mapeará las entidades
spring.jpa.properties.hibernate.default_schema=products_db

# ============================================================
# Configuración de Springdoc OpenAPI (Swagger UI)
# ============================================================

# Ordena los endpoints en la UI por método HTTP
springdoc.swagger-ui.operationsSorter=method

# ============================================================
# Información de la Aplicación (aparece en Swagger UI)
# ============================================================
spring.application.name=products-api

# ============================================================
# GraphQL - configuracion para habilitar GraphiQL y definir la ruta de acceso a GraphQL
# ============================================================
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true

# ============================================================
# Configuración de MongoDB
# ============================================================

spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.username=growShop
spring.data.mongodb.password=GrowSh0p
spring.data.mongodb.database=GrowShop
spring.data.mongodb.authentication-database=admin

# ============================================================
# Logging para MongoDB
# ============================================================

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG
